[package]
name = "uci-ab-test"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = "3.2.0"
clap = { version = "4.5.2", features = ["derive"] }
term_size = "0.3.2"
tokio = { version = "1.36.0", features = ["time", "macros", "rt-multi-thread"] }
